[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = "1.40.0"
